# frozen_string_literal: true

VALID_EMAIL_REGEX = /\A\S+@\S+\.\S+/i
PASSWORD_FORMAT = /\A(?=.*[a-z])(?=.*[0-9])(?=.*\W).{8,16}\z/i
EXPIRED_TIME = 15
PER_PAGE = 10
PER_PAGE_BIG = 15
START_YEAR = 2014
CHECK_IN_MORNING_TIME = 8
CHECK_OUT_AFTERNOON_TIME = 17
CHECK_IN_AFTERNOON_TIME = 13
CHECK_OUT_MORNING_TIME = 12
